### ISSUE TITLE
Add a SwiftUI project for iPadOS

### ISSUE THREAD

**Issue by bofeiw** [ivanvorobei/SwiftUI#34]
Hi,

I created a Calculator App mimicking the iOS Calculator, for iPadOS, using SwiftUI.  
It looks like the enlarged version of the iOS Calculator on iPads, and have the basic functions like simple calculations and copy/paste.

Not sure if it can be added to this repo as an example (https://github.com/bofeiw/ios-calculator-clone-for-ipados), so just making an issue instead of PR.

Thanks!

**Comment by ivanvorobei** [comment]
Hi! 
I think you need create PR)
